[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pykinect_azure"
version = "0.1.0"
description = "Azure Kinect SDK wrapper"
requires-python = ">=3.9"
authors = [
    { name = "Ibai Gorordo" }
]
license = { text = "MIT" }
dependencies = [
    "opencv-python>=4.5.5",
    "numpy>=1.22.2",
    "pyside6>=6.10.0",
    "vispy>=0.15.2",
    "matplotlib>=3.10.8",
    "pynput>=1.8.1",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Topic :: Scientific/Engineering :: Image Recognition",
    "Topic :: Scientific/Engineering :: Human Machine Interfaces",
    "Topic :: Scientific/Engineering :: Visualization",
]

[tool.hatch.build.targets.wheel]
include = ["pykinect_azure"]
source-dir = "src"

[tool.hatch.build.targets.sdist]
exclude = ["/tests", "/examples"]
